### PR TITLE
Milestone 3 three last sections

### PR DESCRIPTION
**Pull request by Amalcxc**
**the magazine and Editor’s pick**

**Newspaper main sections**
US
World
Business
Tech & Science
Culture
Sports
Expert forum

and the **Subscribe / Newsletter**

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED ♻️ 🔴 
-----------
Hello @Amalcxc @vitorelourenco 👋 you are doing an excellent job so far 👏 💯 
There are a few changes to make to complete this milestone 🛠️ see them below  👀 👇 
------------

- [x] Improve your commit messages. Remember that you must write the messages in the imperative. [Here](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) you can read about the formatting rules for an excellent commit message. [Here](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message) you can read about how to change a commit message. You don't need to change the messages that are wrong this time but keep that formatting rules in mind for the next commits. 
- [x] In your README on the "Setup" section, write a step-by-step how to clone your repository, what commands are needed it and where to write those commands. Remember that not everyone is a programmer. 
- [x] Move all the styles that are inside the HTML to CSS. Remember that you shouldn't use styles inside the HTML.
- [x] Check on your footer. The social media icons are making a big space on mobile size. These icons must be down the logo Newsweek. 
- [x] On your tablet check for the bar that scrolls left to right. You can see this bar at the end of the page. There is some item that is overlaid the page, same as the icons on mobile size. Check in the "IN MAGAZINE SECTION"
- [x] Some of your images don't have a link. Please add to all the images a link `a` tag. 
- [ ] The subscribe section has a grey background.  Please add it, it's complicated to see this color in the original one. 
-------
Make these required changes 🛠️ 👆 and send it again for review 👍 
HAPPY CODING!!

images

**Comment by vitorelourenco** [comment]
github clone link was added to the readme file in the setup section

in-line styles were moved to the css 

footer social media icons were shifted to the left on the mobile version 

overflow in the magazine section was handled

images were given an a tag

the background of the page was set to white and the subscribe section background was set to grey

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED ♻️ 🛑 

Hello, @Amalcxc and @vitorelourenco 👋🏿 . This is a good effort. I Love that you have made the changes requested by the previous TSE. However, there are a few more changes to be done kindly check below ⬇️ 

- [x] Files that are not related to the project should not be committed.  Examples include Dsstore, .vsCode.  This will keep your repository clean. These files should be added to the gitIgnore file. Kindly read [this article](https://docs.github.com/en/github/using-git/ignoring-files#create-a-local-gitignore) to learn more about this.

- [x] The first letter of your commit messages should be capitalized. Also, try not to make spelling errors in your commit messages and also check on your tense. This will make your project professional. Kindly learn more on this [here](https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message)

### if you have a question, kindly reach me on slack @peterrobert

### HAPPY CODING 💻

**Comment by vitorelourenco** [comment]
dsstore and vscode were added to the gitignore file.
Future commit messages will be made using the orientations given at https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED 🟢 👏 
-----------
Hello again team 👋 you did an excellent job and an amazing job on the required changes 💪 😄 
---------------
Now you can merge this branch 👏 
HAPPY CODING AND GOOD LUCK WITH THE NEXT PROJECTS 🍀 🤞 

tenor (1)

**Pull request merged**
